### ISSUE TITLE
Crash of node-red server when WDSL file can not be found in flow

### ISSUE THREAD

**Issue by edwin-oetelaar** [chameleonbr/node-red-contrib-soap#4]
2 Sep 17:51:51 - [red] Uncaught Exception:
2 Sep 17:51:51 - Error: WSDL Config Error: Error: read ECONNRESET
    at /usr/src/node-red/node_modules/node-red-contrib-soap/soap-node.js:16:31
    at /usr/src/node-red/node_modules/node-red-contrib-soap/node_modules/soap/lib/soap.js:50:5
    at /usr/src/node-red/node_modules/node-red-contrib-soap/node_modules/soap/lib/soap.js:34:16
    at /usr/src/node-red/node_modules/node-red-contrib-soap/node_modules/soap/lib/wsdl.js:2055:9
    at Request._callback (/usr/src/node-red/node_modules/node-red-contrib-soap/node_modules/soap/lib/http.js:106:14)
    at self.callback (/usr/src/node-red/node_modules/node-red-contrib-soap/node_modules/soap/node_modules/request/request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/src/node-red/node_modules/node-red-contrib-soap/node_modules/soap/node_modules/request/request.js:813:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)

npm info node-red-docker@0.14.6 Failed to exec start script
npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! node-red-docker@0.14.6 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1

**Comment by rossigee** [comment]
There's a fix for that here:

https://github.com/jloupdef/node-red-contrib-soap/commit/21ee0a334c81cb7e4e0b97f3e0965159401ab7e1

In fact, there are quite a few more fixes and tidy-ups on that fork. It's a shame they haven't submitted them back here as PRs.

**Comment by rossigee** [comment]
(I spotted this after I forked and made my own fix for the bug)
